# name   : /api/menu/user
# method : GET
# descript : 사용자의 정보를 조회한다. 토큰 사용

GET http://localhost:9080/api/main/user
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbkBnbWFpbC5jb20iLCJ1c2VyTm0iOiLqtIDrpqzsnpAiLCJsb2dpbklkIjoiYWRtaW5AZ21haWwuY29tIiwiYXV0aFJvbGUiOiJXRUIiLCJleHAiOjIwMDg4MDU1NDgsImlhdCI6MTY5MzQ0NTU0OCwidXNlcklkIjoxLCJhdXRoSWQiOjF9.6ckVmTO0JYlHczHCzi1ejdlfyzWt9ZxC_OXoYntqV2g
