# name   : /api/faq
# method : PUT
# descript : FAQ글울 등록한다.
# param  : boardId - 게시판아이디 / 필수
#        : faqTitle - FAQ글명 / 필수
#        : mainText - FAQ글 본문 / 필수

PUT http://localhost:8080/api/faq
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0MkBnbWFpbC5jb20iLCJ1c2VyTm0iOiLthYzsiqTthLAzMyIsImxvZ2luSWQiOiJ0ZXN0MkBnbWFpbC5jb20iLCJ1c2VyUHciOiIwZmZlMWFiZDFhMDgyMTUzNTNjMjMzZDZlMDA5NjEzZTk1ZWVjNDI1MzgzMmE3NjFhZjI4ZmYzN2FjNWExNTBjIiwiZXhwIjoyMDA2NzU0NTMyLCJpYXQiOjE2OTEzOTQ1MzIsInVzZXJJZCI6NCwiYXV0aElkIjoxfQ.Tc4s3Cioyj6IzpTuo0fsrcXL84PrI_DFjcTG-sO1V_8

{
  "boardId": 2,
  "faqTitle":"FAQ 2번째 글입니다.",
  "mainText": "FAQ 게시판 열심히 만들었어요."
}


