# name   : /api/qna/{id}
# method : PUT
# descript : QNA글울 수정한다.
# param  : qnaTitle - qna명 / 필수
#        : questions - qna 질문 / 필수
#        : hiddenYn - 공개글여부 / 필수
#        : qnaPw - qna 패스워드 / hiddenYn이 Y이면 패스워드를 N이면 빈값을 보낸다.
#        : useYn - 사용여부 / 필수

PUT http://localhost:8080/api/qna/user/2
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0MkBnbWFpbC5jb20iLCJ1c2VyTm0iOiLthYzsiqTthLAzMyIsImxvZ2luSWQiOiJ0ZXN0MkBnbWFpbC5jb20iLCJ1c2VyUHciOiIwZmZlMWFiZDFhMDgyMTUzNTNjMjMzZDZlMDA5NjEzZTk1ZWVjNDI1MzgzMmE3NjFhZjI4ZmYzN2FjNWExNTBjIiwiZXhwIjoyMDA2NzU0NTMyLCJpYXQiOjE2OTEzOTQ1MzIsInVzZXJJZCI6NCwiYXV0aElkIjoxfQ.Tc4s3Cioyj6IzpTuo0fsrcXL84PrI_DFjcTG-sO1V_8

{
  "qnaTitle": "세번째 질문입니다!.",
  "questions": "세번째 질문 내용입니다!.",
  "hiddenYn": "Y",
  "qnaPw": "1111",
  "useYn": "Y"
}


