spring:
  profiles:
    active: dev
  devtools:
    livereload:
      enabled:  true
  jpa:
    database-platform: com.back.config.PostgreSQLConfig
    hibernate:
      ddl-auto: update
    show-sql: false

jwt:
  secret: reolino
  token-validity-in-seconds: 86400



