server:
  port: 8080

spring:
  datasource:
    hikari:
      maximum-pool-size:  4
    url:  jdbc:p6spy:postgresql://localhost:5432/bdrnd
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    username: bdrnd
    password: bdrnd


jwt:
  secret: reolino
  validLongYn: Y
  accessTokenValidTime: 28800000
  refreshTokenValidTime: 86400000
