# name   : /api/post/auth
# method : POST
# descript : 게시글 정보를 목록형으로 가져온다. 사이즈나 페이지는 입력하지 않으면 10개, 1페이지가 기본으로 조회된다.
# param  : boardId - 게시판 아이디 / 필수
#        : authId - 권한아이디 / 필수


POST http://localhost:9080/api/post/auth
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbkBnbWFpbC5jb20iLCJ1c2VyTm0iOiLqtIDrpqzsnpAiLCJsb2dpbklkIjoiYWRtaW5AZ21haWwuY29tIiwiZXhwIjoyMDA3NTExNjYzLCJpYXQiOjE2OTIxNTE2NjMsInVzZXJJZCI6MSwiYXV0aElkIjoxfQ.MWxIkaDNnzjYO9HC7tuMGb-nWgJtGakDKCBTL8izu08

{
  "authId": 3,
  "boardId": 1
}

