# name   : api/item/auth/mine
# method : POST
# descript : 내 권한의 목록을 표시한다. 콤보박스 사용

POST http://localhost:9080/api/item/auth/mine
Content-Type: application/json

{
  "userId": 1,
  "authRole": "WEB"
}

