# name   : /api/user
# method : PUT
# param  : userNm - 사용자명 / 선택
#        : loginId - 아이디 / 선택
#        : useYn - 사용여부 / 선택

POST http://localhost:8080/api/user
Content-Type: application/json

{
  "size": 10,
  "page": 1
}



