# name   : /api/user
# method : PUT
# descript : 사용자 정보를 목록형으로 가져온다. 사이즈나 페이지는 입력하지 않으면 10개, 1페이지가 기본으로 조회된다.
# param  : userNm - 사용자명 / 선택
#        : loginId - 아이디 / 선택
#        : useYn - 사용여부 / 선택
#        : size - 페이지당 개수/ 선택
#        : page - 현재페이지 / 선택

POST http://localhost:9080/api/user
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbkBnbWFpbC5jb20iLCJ1c2VyTm0iOiLqtIDrpqzsnpAiLCJsb2dpbklkIjoiYWRtaW5AZ21haWwuY29tIiwiZXhwIjoyMDA3NTExNjYzLCJpYXQiOjE2OTIxNTE2NjMsInVzZXJJZCI6MSwiYXV0aElkIjoxfQ.MWxIkaDNnzjYO9HC7tuMGb-nWgJtGakDKCBTL8izu08

{

}



