# name   : /api/user/{id}
# method : PUT
# descript : 사용자가 자신의 정보를 수정한다.
# param  : userNm - 사용자명 / 필수 / 최소 2자에서 10자사이로 입력
#        : telNo - 휴대폰 / 필수 / 휴대폰번호형식 제한
#        : useYn - 사용여부 / 필수

PUT http://localhost:9080/api/user/5
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0MkBnbWFpbC5jb20iLCJ1c2VyTm0iOiLthYzsiqTthLAyIiwibG9naW5JZCI6InRlc3QyQGdtYWlsLmNvbSIsInVzZXJQdyI6IjBmZmUxYWJkMWEwODIxNTM1M2MyMzNkNmUwMDk2MTNlOTVlZWM0MjUzODMyYTc2MWFmMjhmZjM3YWM1YTE1MGMiLCJleHAiOjIwMDU2MDg2MDcsImlhdCI6MTY5MDI0ODYwNywidXNlcklkIjo0fQ.dCbqTLt_sYgNWyskxKTVQTFBuciXp9YCWiZ5CpGk5Ts

{
  "userNm": "테스터aa",
  "useYn": "Y",
  "userPw": "1qaz2wsx!@",
  "telNo" : "01012345678"
}


