# name   : /api/certification
# method : POST
# param  : loginId - 로그인 아이디 / 필수
#        : userPw - 비밀번호 / 필수

POST http://localhost:8080/api/certification
Content-Type: application/json

{
  "loginId":"test2@gmail.com",
  "userPw": "1111",
  "loginDevice":"WEB",
  "deviceBrowser": "Chrome"
}
