# name   : /api/user
# method : PUT
# param  : loginId - 사용자명 / 필수 / 로그인 아이디
#        : userPw - 아이디 / 필수 / 비밀번호
#        : device - 접속장비 / 선택

POST http://localhost:8080/api/sample/login
Content-Type: application/json

{
  "loginId":"test1@gmail.com",
  "userPw": "a123123!",
  "device": "WEB"
}


