# name   : /api/certification
# method : POST
# param  : loginId - 로그인 아이디 / 필수
#        : userPw - 비밀번호 / 필수
#        : loginDevice - 접속장비 / 선택
#        : deviceBrowser - 브라우저 / 선택

POST http://localhost:8080/api/login
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0MkBnbWFpbC5jb20iLCJ1c2VyTm0iOiLthYzsiqTthLAzMyIsImxvZ2luSWQiOiJ0ZXN0MkBnbWFpbC5jb20iLCJ1c2VyUHciOiIwZmZlMWFiZDFhMDgyMTUzNTNjMjMzZDZlMDA5NjEzZTk1ZWVjNDI1MzgzMmE3NjFhZjI4ZmYzN2FjNWExNTBjIiwiZXhwIjoyMDA1NjEwNjkxLCJpYXQiOjE2OTAyNTA2OTEsInVzZXJJZCI6NH0.kGSGH9Q1VomglYmSkVKSCUYswY7Bz5BoSR3hZ4Cw-ZI

{
  "loginId":"admin@gmail.com",
  "userPw": "1234"
}

