CREATE TABLE ws.tb_user (
    id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
    login_id varchar(50) NOT NULL,
    user_nm varchar(50) NULL,
    user_pw varchar(255) NULL,
    tel_no varchar(20) NULL,
    last_login_at timestamp NULL,
    login_fail_cnt int4 NOT NULL DEFAULT 0,
    pw_init_yn varchar(1) NULL DEFAULT 'N'::character varying,
    created_at timestamp NOT NULL,
    created_id int8 NULL,
    updated_at timestamp NOT NULL,
    updated_id int8 NULL,
    use_yn varchar(1) NULL DEFAULT 'Y'::character varying,
    CONSTRAINT tb_user_pkey PRIMARY KEY (id)
);

CREATE TABLE ws.tb_login_history (
    id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
    user_id int8 NULL,
    device_browser varchar(100) NULL,
    login_device varchar(10) NULL,
    access_token text NULL,
    refresh_token text NULL,
    created_at timestamp NULL,
    CONSTRAINT tb_login_history_pkey PRIMARY KEY (id),
    CONSTRAINT tb_login_history_fk FOREIGN KEY (user_id) REFERENCES ws.tb_user(id)
);


CREATE TABLE ws.tb_auth (
    id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
    auth_nm varchar(50) NULL,
    auth_role varchar(20) NULL,
    auth_val varchar(20) NULL,
    memo varchar(100) NULL,
    ord varchar(10) NULL,
    mainUrl varchar(255) NULL,
    created_at timestamp NOT NULL,
    created_id int8 NULL,
    updated_at timestamp NOT NULL,
    updated_id int8 NULL,
    use_yn varchar(1) NULL DEFAULT 'Y'::character varying,
    CONSTRAINT tb_auth_pkey PRIMARY KEY (id)
);

CREATE TABLE ws.tb_user_auth (
    id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
    auth_id int8 NULL,
    user_id int8 NULL,
    created_at timestamp NOT NULL,
    created_id int8 NULL,
    updated_at timestamp NOT NULL,
    updated_id int8 NULL,
    use_yn varchar(1) NULL DEFAULT 'Y'::character varying,
    CONSTRAINT tb_user_auth_pkey PRIMARY KEY (id),
    CONSTRAINT tb_user_auth_fk FOREIGN KEY (user_id) REFERENCES ws.tb_user(id),
    CONSTRAINT tb_user_auth_fk_1 FOREIGN KEY (auth_id) REFERENCES ws.tb_auth(id)
);


CREATE TABLE ws.tb_menu (
    id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
    auth_role varchar(20) NULL,
    menu_lv int4 NOT NULL,
    menu_nm varchar(50) NULL,
    menu_type varchar(20) NULL,
    ord int4 NOT NULL,
    prn_menu_id int4 NULL,
    url varchar(255) NULL,
    board_id int8 NULL,
    board_type varchar(20) NULL,
    created_at timestamp NOT NULL,
    created_id int8 NULL,
    updated_at timestamp NOT NULL,
    updated_id int8 NULL,
    use_yn varchar(1) NULL DEFAULT 'Y'::character varying,
    CONSTRAINT tb_menu_pkey PRIMARY KEY (id)
);


CREATE TABLE ws.tb_menu_auth (
    id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
    auth_id int8 NULL,
    menu_id int8 NULL,
    created_at timestamp NOT NULL,
    created_id int8 NULL,
    updated_at timestamp NOT NULL,
    updated_id int8 NULL,
    use_yn varchar(1) NULL DEFAULT 'Y'::character varying,
    CONSTRAINT tb_menu_auth_pkey PRIMARY KEY (id),
    CONSTRAINT tb_menu_auth_fk FOREIGN KEY (auth_id) REFERENCES ws.tb_auth(id),
    CONSTRAINT tb_menu_auth_fk_1 FOREIGN KEY (menu_id) REFERENCES ws.tb_menu(id)
);


CREATE TABLE ws.tb_code_grp (
    id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
    code_grp_nm varchar(50) NULL,
    code_grp_val varchar(20) NULL,
    created_at timestamp NOT NULL,
    created_id int8 NULL,
    updated_at timestamp NOT NULL,
    updated_id int8 NULL,
    use_yn varchar(1) NULL DEFAULT 'Y'::character varying,
    CONSTRAINT tb_code_grp_pkey PRIMARY KEY (id)
);


CREATE TABLE ws.tb_code (
    id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
    code_nm varchar(50) NULL,
    code_val varchar(20) NULL,
    memo varchar(100) NULL,
    ord varchar(10) NULL,
    prn_code_val varchar(20) NULL,
    code_grp_id int8 NULL,
    created_at timestamp NOT NULL,
    created_id int8 NULL,
    updated_at timestamp NOT NULL,
    updated_id int8 NULL,
    use_yn varchar(1) NULL DEFAULT 'Y'::character varying,
    CONSTRAINT tb_code_pkey PRIMARY KEY (id),
    CONSTRAINT tb_code_fk FOREIGN KEY (code_grp_id) REFERENCES ws.tb_code_grp(id)
);


CREATE TABLE ws.tb_board (
    id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
    board_title varchar(100) NULL,
    board_type varchar(20) NULL,
    attach_yn varchar(1) NULL,
    comment_yn varchar(1) NULL,
    memo varchar(100) NULL,
    created_at timestamp NOT NULL,
    created_id int8 NULL,
    updated_at timestamp NOT NULL,
    updated_id int8 NULL,
    use_yn varchar(1) NULL DEFAULT 'Y'::character varying,
    CONSTRAINT tb_board_pkey PRIMARY KEY (id)
);

CREATE TABLE ws.tb_board_auth (
    id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
    auth_id int8 NULL,
    board_id int8 NULL,
    created_at timestamp NOT NULL,
    created_id int8 NULL,
    updated_at timestamp NOT NULL,
    updated_id int8 NULL,
    use_yn varchar(1) NULL DEFAULT 'Y'::character varying,
    CONSTRAINT tb_board_auth_pkey PRIMARY KEY (id),
    CONSTRAINT tb_board_auth_fk FOREIGN KEY (board_id) REFERENCES ws.tb_board(id),
    CONSTRAINT tb_board_auth_fk_1 FOREIGN KEY (auth_id) REFERENCES ws.tb_auth(id)
);

CREATE TABLE ws.tb_post (
    id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
    post_title varchar(100) NULL,
    main_text text NULL,
    view_cnt int4 NOT NULL,
    board_id int8 NULL,
    created_at timestamp NOT NULL,
    created_id int8 NULL,
    updated_at timestamp NOT NULL,
    updated_id int8 NULL,
    use_yn varchar(1) NULL DEFAULT 'Y'::character varying,
    CONSTRAINT tb_post_pkey PRIMARY KEY (id),
    CONSTRAINT tb_post_fk FOREIGN KEY (board_id) REFERENCES ws.tb_board(id)
);


CREATE TABLE ws.tb_faq (
   id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
   faq_title varchar(255) NULL,
   main_text text NULL,
   view_cnt int4 NOT NULL,
   board_id int8 NULL,
   created_at timestamp NOT NULL,
   created_id int8 NULL,
   updated_at timestamp NOT NULL,
   updated_id int8 NULL,
   use_yn varchar(1) NULL DEFAULT 'Y'::character varying,
   CONSTRAINT tb_faq_pkey PRIMARY KEY (id),
   CONSTRAINT tb_faq_fk FOREIGN KEY (board_id) REFERENCES ws.tb_board(id)
);


CREATE TABLE ws.tb_qna (
   id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
   qna_title varchar(255) NULL,
   questions varchar(255) NULL,
   main_text text NULL,
   hidden_yn varchar(255) NULL,
   qna_pw varchar(255) NULL,
   view_cnt int4 NOT NULL,
   board_id int8 NULL,
   created_at timestamp NOT NULL,
   created_id int8 NULL,
   updated_at timestamp NOT NULL,
   updated_id int8 NULL,
   response_id int8 NULL,
   response_at timestamp NULL,
   use_yn varchar(255) NULL DEFAULT 'Y'::character varying,
   response_yn varchar(1) NULL,
   CONSTRAINT tb_qna_pkey PRIMARY KEY (id),
   CONSTRAINT tb_qna_fk FOREIGN KEY (board_id) REFERENCES ws.tb_board(id)
);
