# name   : /api/menuAuth/{menuId}
# method : PUT
# descript : 메뉴 권한울 등록한다.
# param  : updatedRows - 메뉴 권한 수정된 목록 (authId, useYn)
#        : authId - 권한아이디 / 필수
#        : useYn - 사용여부 / 필수

PUT http://localhost:9080/api/menuAuth/12
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0MkBnbWFpbC5jb20iLCJ1c2VyTm0iOiLthYzsiqTthLAyIiwibG9naW5JZCI6InRlc3QyQGdtYWlsLmNvbSIsInVzZXJQdyI6IjBmZmUxYWJkMWEwODIxNTM1M2MyMzNkNmUwMDk2MTNlOTVlZWM0MjUzODMyYTc2MWFmMjhmZjM3YWM1YTE1MGMiLCJleHAiOjIwMDU2MDg2MDcsImlhdCI6MTY5MDI0ODYwNywidXNlcklkIjo0fQ.dCbqTLt_sYgNWyskxKTVQTFBuciXp9YCWiZ5CpGk5Ts

{
  "updatedRows": [
    {
      "authId" : 1,
      "useYn" : "Y"
    },
    {
      "authId" : 2,
      "useYn" : "Y"
    },
    {
      "authId" : 3,
      "useYn" : "Y"
    }
  ]

}


