# name   : /api/menu
# method : PUT
# descript : 메뉴를 등록한다.
# param  : menuNm - 메뉴명 / 필수 / 최대 30자
#        : menuLv - 메뉴레벨 / 필수
#        : prnMenuId - 부모메뉴아이디 / 메뉴레벨이 2인경우 필수로 넣어주세요.
#        : url - 메뉴도메인 / 선택 /200자,영문만
#        : menuType - 메뉴유형 / 필수 / DOMAIN or BOARD
#        : useYn - 사용여부 / 필수
#        : authRole - 권한구분 / 필수
#        : ord - 순서 / 선택 / 없으면 99
#        : boardId - 게시판아이디 / 선택 / 메뉴유형이 BOARD일때 저장
#        : boardType - 게시판유형 / 선택 / 메뉴유형이 BOARD일때 저장


PUT http://localhost:8080/api/menu
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0MkBnbWFpbC5jb20iLCJ1c2VyTm0iOiLthYzsiqTthLAyIiwibG9naW5JZCI6InRlc3QyQGdtYWlsLmNvbSIsInVzZXJQdyI6IjBmZmUxYWJkMWEwODIxNTM1M2MyMzNkNmUwMDk2MTNlOTVlZWM0MjUzODMyYTc2MWFmMjhmZjM3YWM1YTE1MGMiLCJleHAiOjIwMDU2MDg2MDcsImlhdCI6MTY5MDI0ODYwNywidXNlcklkIjo0fQ.dCbqTLt_sYgNWyskxKTVQTFBuciXp9YCWiZ5CpGk5Ts

{
  "menuNm": "FAQ정보1",
  "menuLv":2,
  "prnMenuId": 3,
  "url": "/page/board/faq/list/init",
  "menuType": "DOMAIN",
  "boardVal": "",
  "useYn": "Y",
  "authRole": "WEB",
  "ord" : 4
}


